language: node_js
version: 1.0
node_js:
- 12.4.0
cache:
  directories:
  - node_modules
dist: trusty
install:
- npm install
script:
- npm run build
notifications:
  email:
  - ebrehault@gmail.com
before_deploy: if [[ $TRAVIS_TAG ]]; then cd dist/grange-form; else git config --global
  user.email "build@travis-ci.com" && git config --global user.name "Travis CI" &&
  export PACKAGE_VERSION=$(npm run get_version | tail -n 1) && echo "TAGGING $PACKAGE_VERSION..."
  && git tag $PACKAGE_VERSION; fi
deploy:
  - provider: releases
    api_key:
      secure: Tl+5TxT3Mat2s3dwRLuS/WlCB9UHV4pwOrRYUo07gVO8STZIKuO0TL0ngGOeV5jHoUiU9SGGekG5hNK/ZgfrKfp7tCTRsra+TAOKSdFUGqsQX8k2pAH0YT67+9lwE41XTdYlvSe8dvJtSQEESW4ZLCkPBXMIrszDAuf2UW8rP5tUkflvPFe7VR5QVlRJf6nqEQD77PoLcfiE+p21GzX7wSpjELDcw1L+QDMP/YSjfBmEASISsNtkIGwSj5RDYP218ZpCy8/BLKHyuw8suTU89U5448bmFgDA5/Jmm0jTpJspvO4Wkf6DuO7Vglx0TJfsF2DYEn+T7Gcpj8nLy0w7OPrIzKm0svzAHY1KwMm4ckYLPHTkjJd4gWE0K9//N90DzetfPX622/As4vvXd40OvDS5Ooj/wXhu/Zduzl08T1KPN+ZLXqTHQDqWCL8QWqsecWXBf0Ljg0mHoQcFFoHYPMxTUlUSFlfSIju3eJBKk9jNae3RANiFPag/GC8MuLh83VxXkSKEq7AtD+McVb9sbghQGy1mN64AkuC8pttY+LcXdZZBipYlg7I7dJH5zR9KGtgHcBGnTB65dwaZPzzHzktZSw8Al15c9RcxZg7cOfeqRgEKyDdXJUorwt7zE3+oELa8MGUt3CIzYKmYLhHhopUJTRf09UnwEhjrLIR1yGc=
    name: Build $PACKAGE_VERSION
    on:
      repo: guillotinaweb/grange-form
      branch: master
  - provider: npm
    edge: true
    email: ebrehault@gmail.com
    skip_cleanup: true
    api_key:
      secure: I201jzbu92ySFeMrc/aHUdsIbQMq1vHEtr2Ew2LM48aXDE5j3lHELePGUOVpe5MUyIoeYHJ4M7t9Ba95xILJ7xzZx/7uezHuBLSWYfXIH0EG9rlEI3XF0DAZpjRfxNTZyRxmSpAs/rtMZw02EeLXNbAptsVVBc+p2FmE6QITE6SzW3co9wZX4J7AOMJZscq54xg5HRF9tTSdqIos2GLwqey90nzCSwguH8YOORn9odj//jw8DhQENeS4cVpehQ4i1PJkJ10gRK6NvTMibTqZ22MYqQNLJ68cH8dbdAuGM2yoKnHrWQ1jU4H6yKmo+I9PrslOM2bJnbHdeplmvQbOB9XPzadz//mMkU0P9P42hWunPOIVyCX8w4V34xGNVIr6yjLbhF4hNl/WCRadqIuIrxqRk8lnZBZa79Bm+SUUXj93LAvNgz36fJxXWHlkkPx7nFM/hO+E5bBvG1D7y1eIKOMiNiDrBkFU18eqBA3YHY5mwQtYStPYgJa8nNk5gDa2OXnc+zMHwJ60YH7fTWEaMWNRhDA9t/iiY7T6f1Ym3szOqDTsfQiPlFUj4LW3SkYLdzuLrkN6h3d0YiOKY73CJD/JBWwzyu8hGVZkykmnu/e+Y2F5+3O0fSKpqds+wCLB4Mk3ESdO+F6sVg3RtO4xjwebpHGglMq/TE/CoTYFD8A=
    on:
      tags: true
      repo: guillotinaweb/grange-form
      branch: master
