language: node_js
version: 1.0
node_js:
- 12.4.0
cache:
  directories:
  - node_modules
dist: trusty
install:
- npm install
script:
- npm run build
notifications:
  email:
  - ebrehault@gmail.com
jobs:
  include:
    - stage: Tagging
      if: (branch = master) AND (tag IS blank)
      after_success: source ./deploy.sh
      deploy:
        provider: releases
        api_key:
          secure: ZT2iAG92zgpILjAXEDyQWIVQAyLF0WxWjajBM9yGMSIMQ7quoCFP0/weAd1BPBrddt6nbHX3tBi3Kjr9JbIg4ywGRl5Bn3XSSrmQA001eYVD1SgxZR1H2FqUqR1JPWSRis4/BIKbrXB4aobJ6AZU0tYtPQjLS8LwVcBRWmFlP9l0zie7N8DMPmo3UsoVkGVsJiSb/rf2FnBh9bdnWhB8rDKdQ5KPyOhAXkzxiYYTC9VZm5TF3jCgVSZXmZFD2EgDM1SAcworYf2fyWJ325A5MbtocDK1Yqe0AWCWMEhUJksJ41gGwZxXzC4dUth5w+ZX5LPfVj9VwlDvlmmfFAZXnf7Xa91ka8D7PT7Cfd1Hyx8ayUsBzR3NDhmM1bSL3KjXgX7JyBLAO/hljruGqpCGxMp7f0OyYtEY9VDMTzHuP0t9NsF4sO4EYKeZNvsmrxDI9Dypore0TgyBXZ8TVJZ1bKAZ5EGy7bdmrCL8QAnrXNyImoE+1xuiXRqufRbffJfFonokY2jNALrCURcaN6t4bGDIlVdPd39x7OYJ3nQ94HNDg8QloHEo/IZAqEyjDDi6MstEQ5/CSUusFVY7/b1XAaagCpJPB1v7zMk5+UgePGzYm/KVQZGqkqNKTbtFweWMANBfzdAQDhozAfaMoEOZvvZAyekahMKC2Tqp2RzCBt0=
        name: Build $PACKAGE_VERSION
        on:
          repo: guillotinaweb/grange-form
          branch: master
          tags: true
    - stage: NPM release
      if: tag IS present
      before_deploy: cd dist/grange-form
      deploy:
        provider: npm
        edge: true
        email: ebrehault@gmail.com
        skip_cleanup: true
        api_key:
          secure: BRwVL4eW5qMZa+oWxmq7KsZ40yS5F0jOqJhfXqNwFJn7h/zvLnrhTXtGUhrBVRJDnKNJIo/G9mv95L9xw+MfFXXojaahA02FDk8yeOhDxZDjsw+Xb/czSHuebauxlFuL69IbkeHy20oBhhWVPdVMM91A7fXS2dkSewDyn5Xx+1vtuT7r8b5SgZd6IoTsd5DsrplnUOlowLUpk36B36e19DjUSs0GCxRq74hlsf4QoCAvn1D41Mu7zThmEYZbc2ClmWr62aF8p//Azt8IEXlPmnmeIRNYS9dP27CigZRml+cm9l1mbhDloy96OHXNnf9giHRCsRAYb+BoyOh15bI06WgNtaFMPhdOM6gbPZ9OvI/Jb9t5M3oRdhNmtwgwXWV94YNIy3UJbStq+F8IbEPiTVT1H3CKTfQzo75fSQexgDod/vYRwEYE1BQcbigNdIoM4FVybwQY6h47qBGjtCqMghLZO/7kZ5nEXzEL+r69ZScusM7zP7UTa12Y+ch0m2y0yjDWilE5MKTywxWqdriALszRSr1S7paJG4U+qdA/V/yMy/iCi4ZNB/xe9j2hkNALvMY5IPGM9QNErbqLU24kCG+5D1EBa3/KQM85sjVUoFP6DUTEmzUvYgcNz8TCozXF0JV1xUFG+j8B6VyCpBJleG6BFoIa1pS38Xpd4ky8D/0=
        on:
          tags: true
          repo: guillotinaweb/grange-form
          branch: master
