language: node_js
version: 1.0
node_js:
- 12.4.0
cache:
  directories:
  - node_modules
dist: trusty
install:
- npm install
script:
- npm run build
notifications:
  email:
  - ebrehault@gmail.com
before_deploy: if [[ $TRAVIS_TAG ]]; then cd dist/grange-form; else git config --global
  user.email "build@travis-ci.com" && git config --global user.name "Travis CI" &&
  export PACKAGE_VERSION=$(npm run get_version | tail -n 1) && echo "TAGGING $PACKAGE_VERSION..."
  && git tag $PACKAGE_VERSION; fi
deploy:
  - provider: releases
    api_key:
      secure: ZT2iAG92zgpILjAXEDyQWIVQAyLF0WxWjajBM9yGMSIMQ7quoCFP0/weAd1BPBrddt6nbHX3tBi3Kjr9JbIg4ywGRl5Bn3XSSrmQA001eYVD1SgxZR1H2FqUqR1JPWSRis4/BIKbrXB4aobJ6AZU0tYtPQjLS8LwVcBRWmFlP9l0zie7N8DMPmo3UsoVkGVsJiSb/rf2FnBh9bdnWhB8rDKdQ5KPyOhAXkzxiYYTC9VZm5TF3jCgVSZXmZFD2EgDM1SAcworYf2fyWJ325A5MbtocDK1Yqe0AWCWMEhUJksJ41gGwZxXzC4dUth5w+ZX5LPfVj9VwlDvlmmfFAZXnf7Xa91ka8D7PT7Cfd1Hyx8ayUsBzR3NDhmM1bSL3KjXgX7JyBLAO/hljruGqpCGxMp7f0OyYtEY9VDMTzHuP0t9NsF4sO4EYKeZNvsmrxDI9Dypore0TgyBXZ8TVJZ1bKAZ5EGy7bdmrCL8QAnrXNyImoE+1xuiXRqufRbffJfFonokY2jNALrCURcaN6t4bGDIlVdPd39x7OYJ3nQ94HNDg8QloHEo/IZAqEyjDDi6MstEQ5/CSUusFVY7/b1XAaagCpJPB1v7zMk5+UgePGzYm/KVQZGqkqNKTbtFweWMANBfzdAQDhozAfaMoEOZvvZAyekahMKC2Tqp2RzCBt0=
    name: Build $PACKAGE_VERSION
    on:
      repo: guillotinaweb/grange-form
      branch: master
  - provider: npm
    edge: true
    email: ebrehault@gmail.com
    skip_cleanup: true
    api_key:
      secure: lysNsUNcpi11XMlkoHEgObXk++BnjEO29lhItfwei1fRWSgSHkUiSVMlGSNMq2RRnCRQ4XLmmJgVoW3jLWI9PD90h6OcNMl8VeGScZ3Fd6u3rFv73kZZrfaQoBrdleZMbfj+0METD0u2U/RbHnUkNI9g1YBboxlH2oMuuWYvMyyjW3X5UmdXPcmLq7o3awJw1Bq0GM+cJTn1f3Yx90MqNJMZu6QY1KCdHXiuGhm+QbkwYADz4nInp4UxTGFQdLY9vliHa27zn/BigGimhfIAyT8LKww5qcz+IyUIbQ+1T3HnitePr/OLHRblEOI7+7JsY9ytrthhx3wIrUHigtvKWxVNhOMbNeNPKMqIkZZ0cdOF3RlWSWwVa83FZ9gjJmNuHfd9T7UCMwAd8WsQnnkcJnNoDugAGJk+hyIwoPDAjfFehEWPKs32Upl0EDyZP9nqyueDadE6m4ll77M04J0kSL/2+94eRC+fYnCqNgLlZ5dXMEXWyi0bh3muImGQfvPeLdz8Ob7BzmHUC7eAZycvZgZsntpFJgukhffamE/nVhGIUMR0B1qJKoQOuP8ETKFfVh5E/x6c6uLij2OnZjQpwnztYcgBF6wZnSQmZNynIrMC3FsumtXqCjROSNlkEDLaBrQi7B0nzG0C41F8GAFMDgporuFkdc6YtSyW+8hVbHc=
    on:
      tags: true
      repo: guillotinaweb/grange-form
      branch: master
